version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    tty: true
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
    environment:
      MYSQL_URL: ${MYSQL_URL}
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db